services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/app

  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dev
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: