networks:
  app_net:
    ipam:
      config:
        - subnet: 198.20.0.0/16

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/app
    networks:
      app_net:
        ipv4_address: 198.20.0.10

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8888:80
    volumes:
      - .:/var/www/app
    networks:
      app_net:
        ipv4_address: 198.20.0.20

  database:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: !ChangeMe!
      POSTGRES_USER: app
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      app_net:
        ipv4_address: 198.20.0.30

volumes:
  db-data:
