version: '3'

networks:
  app_net:
    ipam:
      config:
        - subnet: 198.20.0.0/16

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
    networks:
      app_net:
        ipv4_address: 198.20.0.10
    command: ["/bin/sh", "-c", "composer install && bin/console d:m:m --no-interaction && php-fpm"]

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
    networks:
      app_net:
        ipv4_address: 198.20.0.20

  mysql:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 198.20.0.30

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      app_net:
        ipv4_address: 198.20.0.40

volumes:
  db-data:
